AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless-ojichat
Globals:
  Function:
    Timeout: 5

Resources:
  OjiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: oji/
      Handler: bootstrap
      Runtime: provided.al2
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /oji
            Method: POST
Outputs:
  OjiAPI:
    Description: API Endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/oji"
